### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by ValdikSS** [ValdikSS/GoodbyeDPI#42]
- [ ] IPv6 support
- [ ] Option to disable `Connection: close` header check for passive blocker
- [ ] Option to add additional ports for Window Size modification
- [ ] Tray icon
- [ ] White/black lists

Optional:
- [ ] Run as Windows Service

**Comment by miaomiaosoft** [comment]
Hello there!
I live in China,
The internet censorship and blockade here are equally serious,
Some people say that Russia introduced the notorious firewall technology from China,
But luckily I found GoodbyeDPI,
It applies to my network,
Can break through most of the blockade,
Although there are several sites will be abnormal,
But this is very good!
At the same time I am looking forward to the white list function.

**Thank you very much, great job!**

**Comment by ValdikSS** [comment]
@miaomiaosoft Glad to hear that, but please don't post information off the ticket topic.

**Comment by ValdikSS** [comment]
**Make Host value randomly MixedCase**
Implemented in commit c7905f0b317c48ce8b0feb7601461abd24966b42

**Comment by ValdikSS** [comment]
**Make SNI value randomly MixedCase**
SNI can't be modified without TLS termination as it got verified in TLS handshake.

**Comment by ValdikSS** [comment]
**Option to add additional ports for Window Size modification**
Implemented in commit 61e39bc095f02be6daf279e57f3038a3c17e9cc1 & 9b9be302cbe22ef647fa567c4cbe191be9991cbe

**Comment by ValdikSS** [comment]
**DNS redirection**
Implemented in commit a182f52207959b9bbf5ed5a1afa4d1b3a2adfc2b (experimental)

**Comment by ValdikSS** [comment]
**Tray icon**
Tray icon is implemented (not yet commited)

**Comment by ValdikSS** [comment]
**Blacklist**
Implemented in commit bfed8638e58401fd725c6274e9bf65672c4f34ec

**Comment by hooddy** [comment]
I'm vote for Windows Service.

**Comment by ValdikSS** [comment]
**New DPI TCP connection cloak technique**
HTTP Persistent (keep-alive) fragmentation. Implemented in commit a49d38cb285d58b27325939a965d4bb891d71f4d

**Comment by ValdikSS** [comment]
**Windows Service support**
Implemented in commit 23babdc8facff4cc9528bcace843e79615d2676f

**Comment by ValdikSS** [comment]
**IPv6 support**
Preliminary IPv6 support has been added into ipv6 branch, not yet merged.

**Comment by sgeto** [comment]
Any update on the tray icon feature?

**Comment by ValdikSS** [comment]
@sgeto It's probably won't be commited. I decided to make proper GUI.

**Comment by sgeto** [comment]
That's great. It would be nice though if the GUI could be minimized to the system tray.

**Comment by ValdikSS** [comment]
Full IPv6 support is commited to ipv6 branch, merged with master branch.

**Comment by KOLANICH** [comment]
Do we really need DNS redirection in GDPI? Why not just use dnscrypt (it has a chicken & egg problem: if it cannot resolve names of dns servers it stops working, this definitely needs to be fixed, but I guess for this use case it doesn't make much trouble) for that?

**Comment by ValdikSS** [comment]
@KOLANICH, redirecting UDP DNS queries is easy to implement with WinDivert. Dnscrypt is another third-party software and protocol.

**Comment by KOLANICH** [comment]
@ValdikSS I know. But since encrypted and authenticated communications are better than unencrypted or authenticated I guess this is unneeded. I have encountered a network where all DNS queries, no matter if they targeted to ISP's or other DNS server, were answered by ISP's one. DNSCrypt have solved this problem.

**Comment by ValdikSS** [comment]
@KOLANICH, I know about this issue, that's why `cmd` file contains Yandex DNS on unusual `1253` port by default. It's less likely this port will be redirected to ISP's DNS server.

**Comment by cheytacllc** [comment]
@ValdikSS i forked GUI for GoodByeDPI then i added scheduling feature and merged with dnscrypt-proxy in one UI https://github.com/cheytacllc/GUI-for-GoodbyeDPI

**Comment by rawaludin** [comment]
Thanks for this! I really hope the mac version could be released, I can't do C though so can't help much :(

**Comment by ExaltedReaper** [comment]
Бро, я недоволен твоим восприятием проблем людей в специальном для этого разделе.
Я сделал пост с комплексной проблемой, которой нет в твоем FAQ и объяснил в комментариях человеку, почему мой вопрос под этот "ответ из FAQ" не подпадает, а ты кинул меня с моей проблемой в общую кучу закрыв обсуждение с комментарием: "Ответ в FAQ"... Некрасиво как-то.
Ты давай развернутый ответ при закрытии темы, чтобы люди понимали что к чему, потыкай носом в цитататы из "твоего FAQ" и объясни, почему именно "это" является ответом на мой вопрос. Потому что если для тебя что-то очевидно, то для людей несведущих в теме все совсем не очевидно.
Я читал, и считаю что нет ответа на мою проблему в "твоем FAQ". В игре античит? Ок, ладно, хуй с этим. Но там так то в обсуждении еще проблема есть.
И я недоволен твоей работой, потому что я для себя никаких ответов, при обращении за помощью, не нашел.
